-- CREATE DATABASE fifa17;
--     WITH
--     OWNER = postgres
--     ENCODING = 'UTF8'
--     TABLESPACE = pg_default
--     CONNECTION LIMIT = -1;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR NOT NULL,
  wins INTEGER NOT NULL DEFAULT 0,
  losses INTEGER NOT NULL DEFAULT 0,
  elo INTEGER NOT NULL DEFAULT 1000,
  draws INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE games (
  id SERIAL PRIMARY KEY NOT NULL,
  winner_id INTEGER NOT NULL,
  loser_id INTEGER NOT NULL,
  winner_elo INTEGER NOT NULL,
  loser_elo INTEGER NOT NULL,
  winner_score INTEGER NOT NULL,
  loser_score INTEGER NOT NULL,
  date BIGINT NOT NULL,
  draw BOOLEAN NOT NULL DEFAULT FALSE
);
